program AcceptanceTest;

uses
  Forms,
  TestFramework,
  GUITestRunner,
  duOleDriver in 'units\duOleDriver.pas',
  WebPrinter in '..\..\source\WebFptrSo\Units\WebPrinter.pas',
  LogFile in '..\..\source\Shared\LogFile.pas',
  WException in '..\..\source\Shared\WException.pas',
  JsonUtils in '..\..\source\Shared\JsonUtils.pas',
  DriverError in '..\..\source\Shared\DriverError.pas',
  FileUtils in '..\..\source\Shared\FileUtils.pas',
  duCalculator in 'units\duCalculator.pas',
  WebPrinterImpl in '..\..\source\WebFptrSo\units\WebPrinterImpl.pas',
  Opos in '..\..\source\Opos\Opos.pas',
  Oposhi in '..\..\source\Opos\Oposhi.pas',
  OposFptr in '..\..\source\Opos\OposFptr.pas',
  OposFptrhi in '..\..\source\Opos\OposFptrhi.pas',
  OposEvents in '..\..\source\Opos\OposEvents.pas',
  OposEventsRCS in '..\..\source\Opos\OposEventsRCS.pas',
  DebugUtils in '..\..\source\Shared\DebugUtils.pas',
  OPOSException in '..\..\source\Opos\OposException.pas',
  OposFptrUtils in '..\..\source\Opos\OposFptrUtils.pas',
  OposUtils in '..\..\source\Opos\OposUtils.pas',
  OposServiceDevice19 in '..\..\source\Opos\OposServiceDevice19.pas',
  OposSemaphore in '..\..\source\Opos\OposSemaphore.pas',
  NotifyThread in '..\..\source\Shared\NotifyThread.pas',
  PrinterTypes in '..\..\source\Shared\PrinterTypes.pas',
  StringUtils in '..\..\source\Shared\StringUtils.pas',
  RegExpr in '..\..\source\Shared\RegExpr.pas',
  VersionInfo in '..\..\source\Shared\VersionInfo.pas',
  FiscalPrinterState in '..\..\source\WebFptrSo\units\FiscalPrinterState.pas',
  CustomReceipt in '..\..\source\WebFptrSo\units\CustomReceipt.pas',
  DirectIOAPI in '..\..\source\WebFptrSo\units\DirectIOAPI.pas',
  NonfiscalDoc in '..\..\source\WebFptrSo\units\NonfiscalDoc.pas',
  ServiceVersion in '..\..\source\Shared\ServiceVersion.pas',
  DeviceService in '..\..\source\Shared\DeviceService.pas',
  PrinterParameters in '..\..\source\Shared\PrinterParameters.pas',
  VatRate in '..\..\source\Shared\VatRate.pas',
  ReceiptItem in '..\..\source\WebFptrSo\units\ReceiptItem.pas',
  MathUtils in '..\..\source\WebFptrSo\units\MathUtils.pas',
  WebFptrSO_TLB in '..\..\source\WebFptrSo\WebFptrSO_TLB.pas',
  ItemUnit in '..\..\source\Shared\ItemUnit.pas',
  PrinterParametersX in '..\..\source\Shared\PrinterParametersX.pas',
  PrinterParametersReg in '..\..\source\Shared\PrinterParametersReg.pas',
  CashInReceipt in '..\..\source\WebFptrSo\units\CashInReceipt.pas',
  CashOutReceipt in '..\..\source\WebFptrSo\units\CashOutReceipt.pas',
  SalesReceipt in '..\..\source\WebFptrSo\units\SalesReceipt.pas',
  TextDocument in '..\..\source\WebFptrSo\units\TextDocument.pas',
  uLkJSON in '..\..\source\Shared\uLkJSON.pas',
  duWebPrinterImpl in 'units\duWebPrinterImpl.pas',
  SMFiscalPrinter in '..\..\source\Opos\SMFiscalPrinter.pas',
  OposFiscalPrinter_1_13_Lib_TLB in '..\..\source\Opos\OposFiscalPrinter_1_13_Lib_TLB.pas',
  TLVItem in '..\..\source\WebFptrSo\units\TLVItem.pas',
  duWebPrinter in 'units\duWebPrinter.pas';

{$R *.RES}

begin
  TGUITestRunner.RunTest(RegisteredTests);
end.
