program WebFptrCfg;

uses
  Forms,
  SysUtils,
  gnugettext,
  fmuMain in 'Fmu\fmuMain.pas' {fmMain},
  fmuDevice in 'Fmu\fmuDevice.pas' {fmDevice},
  fmuPages in 'Fmu\fmuPages.pas' {fmPages},
  untUtil in 'Units\untUtil.pas',
  Oposhi in '..\Opos\Oposhi.pas',
  OposUtils in '..\Opos\OposUtils.pas',
  Opos in '..\Opos\Opos.pas',
  OposEvents in '..\Opos\OposEvents.pas',
  OPOSException in '..\Opos\OposException.pas',
  OposFptr in '..\Opos\OposFptr.pas',
  OposFptrhi in '..\Opos\OposFptrhi.pas',
  OposFptrUtils in '..\Opos\OposFptrUtils.pas',
  OposDevice in '..\Opos\OposDevice.pas',
  OposFiscalPrinter_1_12_Lib_TLB in '..\Opos\OposFiscalPrinter_1_12_Lib_TLB.pas',
  DriverError in '..\Shared\DriverError.pas',
  VersionInfo in '..\Shared\VersionInfo.pas',
  DebugUtils in '..\Shared\DebugUtils.pas',
  BaseForm in '..\Shared\BaseForm.pas',
  FileUtils in '..\Shared\FileUtils.pas',
  LogFile in '..\Shared\LogFile.pas',
  WException in '..\Shared\WException.pas',
  RegExpr in '..\Shared\RegExpr.pas',
  JsonUtils in '..\Shared\JsonUtils.pas',
  untPages in 'Units\untPages.pas',
  FptrTypes in 'Units\FptrTypes.pas',
  FiscalPrinterDevice in 'Units\FiscalPrinterDevice.pas',
  fmuFptrLog in 'Fmu\fmuFptrLog.pas' {fmFptrLog},
  TntIniFiles in '..\Shared\TntIniFiles.pas',
  StringUtils in '..\Shared\StringUtils.pas',
  fmuFptrReceipt in 'Fmu\fmuFptrReceipt.pas' {fmFptrReceipt},
  fmuFptrTrailer in 'Fmu\fmuFptrTrailer.pas' {fmFptrTrailer},
  fmuFptrConnection in 'Fmu\fmuFptrConnection.pas' {fmFptrConnection},
  OposEventsRCS in '..\Opos\OposEventsRCS.pas',
  OposSemaphore in '..\Opos\OposSemaphore.pas',
  fmuFptrMiscParams in 'Fmu\fmuFptrMiscParams.pas' {fmFptrMiscParams},
  fmuFptrVatRate in 'Fmu\fmuFptrVatRate.pas' {fmFptrVatRate},
  VatRate in '..\Shared\VatRate.pas',
  uLkJSON in '..\Shared\uLkJSON.pas',
  fmuFptrPayType in 'Fmu\fmuFptrPayType.pas' {fmFptrPayType},
  OposEsc in '..\Opos\OposEsc.pas',
  SerialPorts in '..\Shared\SerialPorts.pas',
  SerialPort in '..\Shared\SerialPort.pas',
  PrinterPort in '..\Shared\PrinterPort.pas',
  DeviceNotification in '..\Shared\DeviceNotification.pas',
  PortUtil in '..\Shared\PortUtil.pas',
  TextReport in '..\Shared\TextReport.pas',
  PosWinPrinter in '..\Shared\PosWinPrinter.pas',
  OposServiceDevice19 in '..\Opos\OposServiceDevice19.pas',
  NotifyThread in '..\Shared\NotifyThread.pas',
  PosEscPrinter in '..\Shared\PosEscPrinter.pas',
  EscPrinter in '..\Shared\EscPrinter.pas',
  ByteUtils in '..\Shared\ByteUtils.pas',
  Semaphore in '..\Opos\Semaphore.pas',
  POSPrinterLog in '..\Opos\POSPrinterLog.pas',
  ServiceVersion in '..\Shared\ServiceVersion.pas',
  DeviceService in '..\Shared\DeviceService.pas',
  uZintBarcode in '..\Shared\uZintBarcode.pas',
  uZintInterface in '..\Shared\uZintInterface.pas',
  SocketPort in '..\Shared\SocketPort.pas',
  ReceiptTemplate in '..\Shared\ReceiptTemplate.pas',
  MockPrinterPort in '..\Shared\MockPrinterPort.pas',
  RawPrinterPort in '..\Shared\RawPrinterPort.pas',
  Translation in '..\Shared\Translation.pas',
  fmuFptrBarcode in 'Fmu\fmuFptrBarcode.pas' {fmFptrBarcode},
  fmuFptrHeader in 'Fmu\fmuFptrHeader.pas' {fmFptrHeader},
  fmuTranslation in 'Fmu\fmuTranslation.pas' {fmTranslation},
  xmlParser in '..\Shared\XMLParser.pas',
  DIOHandler in '..\Shared\DIOHandler.pas',
  DIOHandlers in '..\Shared\DIOHandlers.pas',
  BarcodeUtils in '..\Shared\BarcodeUtils.pas',
  PrinterParameters in '..\WebFptrSo\Units\PrinterParameters.pas',
  PrinterTypes in '..\WebFptrSo\Units\PrinterTypes.pas',
  PayType in '..\WebFptrSo\Units\PayType.pas',
  WebFptrSo_TLB in '..\WebFptrSo\WebFptrSo_TLB.pas',
  DirectIOAPI in '..\WebFptrSo\Units\DirectIOAPI.pas',
  VatCode in '..\WebFptrSo\Units\VatCode.pas',
  PrinterParametersX in '..\WebFptrSo\Units\PrinterParametersX.pas',
  PrinterParametersReg in '..\WebFptrSo\Units\PrinterParametersReg.pas',
  PrinterParametersRegIBT in '..\WebFptrSo\Units\PrinterParametersRegIBT.pas',
  PrinterParametersIni in '..\WebFptrSo\Units\PrinterParametersIni.pas',
  SmIniFile in '..\WebFptrSo\Units\SmIniFile.pas',
  DriverContext in '..\WebFptrSo\Units\DriverContext.pas';

{$R *.RES}
{$R WindowsXP.RES}

begin
  Application.Initialize;
  Application.CreateForm(TfmMain, fmMain);
  Application.Run;
end.



