library WebFptrSo;

uses
  Opos in '..\Opos\Opos.pas',
  Oposhi in '..\Opos\Oposhi.pas',
  OposFptr in '..\Opos\OposFptr.pas',
  OposUtils in '..\Opos\OposUtils.pas',
  OposFptrhi in '..\Opos\OposFptrhi.pas',
  OposException in '..\Opos\OposException.pas',
  WException in '..\Shared\WException.pas',
  oleFiscalPrinter in 'Units\oleFiscalPrinter.pas',
  LogFile in '..\Shared\LogFile.pas',
  OposFptrUtils in '..\Opos\OposFptrUtils.pas',
  WebkassaImpl in 'Units\WebkassaImpl.pas',
  WebFptrSO_TLB in 'WebFptrSO_TLB.pas',
  OposServiceDevice19 in '..\Opos\OposServiceDevice19.pas',
  OposEvents in '..\Opos\OposEvents.pas',
  OposSemaphore in '..\Opos\OposSemaphore.pas',
  NotifyThread in '..\Shared\NotifyThread.pas',
  VersionInfo in '..\Shared\VersionInfo.pas',
  OposEventsRCS in '..\Opos\OposEventsRCS.pas',
  DebugUtils in '..\Shared\DebugUtils.pas',
  DriverError in '..\Shared\DriverError.pas',
  WebkassaClient in 'Units\WebkassaClient.pas',
  JsonUtils in '..\Shared\JsonUtils.pas',
  FiscalPrinterState in 'units\FiscalPrinterState.pas',
  CustomReceipt in 'units\CustomReceipt.pas',
  TextItem in 'units\TextItem.pas',
  MathUtils in 'units\MathUtils.pas',
  NonfiscalDoc in 'units\NonfiscalDoc.pas',
  ServiceVersion in '..\Shared\ServiceVersion.pas',
  DeviceService in '..\Shared\DeviceService.pas',
  CashOutReceipt in 'units\CashOutReceipt.pas',
  CashInReceipt in 'units\CashInReceipt.pas',
  OposPOSPrinter_CCO_TLB in '..\Opos\OposPOSPrinter_CCO_TLB.pas',
  PrinterParameters in '..\Shared\PrinterParameters.pas',
  FileUtils in '..\Shared\FileUtils.pas',
  PrinterParametersX in '..\Shared\PrinterParametersX.pas',
  PrinterParametersIni in '..\Shared\PrinterParametersIni.pas',
  TntIniFiles in '..\Shared\TntIniFiles.pas',
  SmIniFile in '..\Shared\SmIniFile.pas',
  StringUtils in '..\Shared\StringUtils.pas',
  RegExpr in '..\Shared\RegExpr.pas',
  SalesReceipt in 'units\SalesReceipt.pas',
  ReceiptItem in 'units\ReceiptItem.pas',
  OposPtr in '..\Opos\OposPtr.pas',
  OposEsc in '..\Opos\OposEsc.pas',
  TextDocument in 'units\TextDocument.pas',
  PrinterParametersReg in '..\Shared\PrinterParametersReg.pas',
  ComServ in '..\Common\ComServ.pas',
  uLkJSON in '..\Shared\uLkJSON.pas',
  VatRate in '..\Shared\VatRate.pas',
  OposPtrUtils in '..\Opos\OposPtrUtils.pas',
  OposPtrhi in '..\Opos\OposPtrhi.pas',
  OposFiscalPrinter_CCO_TLB in '..\Opos\OposFiscalPrinter_CCO_TLB.pas',
  uZintBarcode in '..\Shared\uZintBarcode.pas',
  uZintInterface in '..\Shared\uZintInterface.pas',
  RecPrinter in 'units\RecPrinter.pas',
  OposDevice in '..\Opos\OposDevice.pas',
  POSPrinterLog in '..\Opos\POSPrinterLog.pas',
  EscPrinter in '..\Shared\EscPrinter.pas',
  ByteUtils in '..\Shared\ByteUtils.pas',
  PosWinPrinter in '..\Shared\PosWinPrinter.pas',
  PrinterPort in '..\Shared\PrinterPort.pas',
  PosEscPrinter in '..\Shared\PosEscPrinter.pas',
  DeviceNotification in '..\Shared\DeviceNotification.pas',
  PortUtil in '..\Shared\PortUtil.pas',
  TextReport in '..\Shared\TextReport.pas',
  SocketPort in '..\Shared\SocketPort.pas',
  SerialPorts in '..\Shared\SerialPorts.pas',
  ReceiptTemplate in '..\Shared\ReceiptTemplate.pas',
  MockPrinterPort in '..\Shared\MockPrinterPort.pas',
  RawPrinterPort in '..\Shared\RawPrinterPort.pas',
  Translation in '..\Shared\Translation.pas',
  DirectIOAPI in 'units\DirectIOAPI.pas',
  xmlParser in '..\Shared\XMLParser.pas',
  DIOHandlers in '..\Shared\DIOHandlers.pas',
  DIOHandler in '..\Shared\DIOHandler.pas',
  DriverContext in '..\Shared\DriverContext.pas',
  PrinterTypes in '..\Shared\PrinterTypes.pas',
  BarcodeUtils in '..\Shared\BarcodeUtils.pas';

exports
  DllGetClassObject,
  DllCanUnloadNow,
  DllRegisterServer,
  DllUnregisterServer;

{$R *.TLB}

{$R *.RES}

begin
end.
